### PR TITLE
Fixing concurrent modification exception when ExtentTest.addlog is called.

### PR DESCRIPTION
**Pull request by virenv**
**Issue:** When we call ExtentTest.addLog we recalculate all the report analytics(collectRunInfo method). This is a costly process and it is required only when we flush reports.

**_Fix:_** I have moved the collectRunInfo to be called only when we do flush on the report. That is when in an ideal design we should be collecting all the information from tests. However, the exiting code seems to be there for a reason. @anshooarora : Please take a look at this PR as it changes the ExtentReports at a fundamental level.

### CODE REVIEW

**Comment by foursyth** [comment]
I was following up on this too and @anshooarora on this too, and he mentioned that is required, but we can condense the amount of computation that happens at this level.

When a user does `extent.getStats()` [here](https://github.com/extent-framework/extentreports-java/blob/master/src/main/java/com/aventstack/extentreports/ExtentReports.java#L399), he/she will not be able to retrieve the current picture of run because flush has not yet occurred.

**Comment by virenv** [comment]
That makes sense. Let me see if we can serve that purpose in a different way.

**Comment by virenv** [comment]
Actually if it is just the stats that we want, we can just update the stats and nothing else. I will update the PR tonight with my proposal.

**Comment by foursyth** [comment]
Yup, just need to condense to update the stats here..

**Comment by virenv** [comment]
@anshooarora  @foursyth: Please take a look at the PR when you get time.

**Comment by foursyth** [comment]
@virenv  why are you flushing when retrieving the stats?  This can have unintended side-affects because the reports will get generated each time.

**Comment by virenv** [comment]
@foursyth : Either we update the status everytime or we do it when someone actually needs it. That is why when someone calls getstatus we generate the report.

**Comment by tondacihak** [comment]
@virenv  hi, Do you know the date of release 4.0.10  version, which will contain that fix?

**Comment by virenv** [comment]
@tondacihak : I was busy over the past two weeks. I will try to push this change by this weekend.

**Comment by virenv** [comment]
@anshooarora and @foursyth : Please spend some time taking a look at this PR. We can merge it as soon as possible if I get a go ahead.

**Comment by virenv** [comment]
I am pushing the change in. So take some time out to review this later, we will incrementally change if there is a comment.

**Pull request merged**
